version: '3.8'

services:
  db:
    image: postgres:13
    container_name: mock_payment_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payments
    ports:
      - "5433:5432"  # Измените хост-порт на 5433
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: mock_payment_service
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db

volumes:
  db_data: